# skeptic's annotated bible utilities for antaytheist

book2url = {
    # OT
    "Genesis": "gen",
    "Exodus": "ex",
    "Leviticus": "lev",
    "Numbers": "num",
    "Deuteronomy": "dt",
    "Joshua": "jos",
    "Judges": "jg",
    "Ruth": "ru",
    "1 Samuel": "1sam",
    "2 Samuel": "2sam",
    "1 Kings": "1kg",
    "2 Kings": "2kg",
    "1 Chronicles": "1chr",
    "2 Chronicles": "2chr",
    "Ezra": "exra",
    "Nehemiah": "neh",
    "Esther": "est",
    "Job": "job",
    "Psalms": "ps",
    "Proverbs": "pr",
    "Ecclesiastes": "ec",
    "Song of Solomom": "sofs",
    "Isaiah": "is",
    "Jeremiah": "jer",
    "Lamentations": "lam",
    "Ezekiel": "ezek",
    "Daniel": "dan",
    "Hosea": "hos",
    "Joel": "jl",
    "Amos": "am",
    "Obadiah": "ob",
    "Jonah": "jon",
    "Micah": "mic",
    "Nahum": "nah",
    "Habakkuk": "hab",
    "Zephaniah": "zeph",
    "Haggai": "hag",
    "Zechariah": "zech",
    "Malachi": "mal",
    # NT
    "Matthew": "mt",
    "Mark": "mk",
    "Luke": "lk",
    "John": "jn",
    "Acts": "acts",
    "Romans": "rom",
    "1 Corinthians": "1cor",
    "2 Corinthians": "2cor",
    "Galatians": "gal",
    "Ephesians": "eph",
    "Philippians": "phil",
    "Collosians": "col",
    "1 Thessalonians": "1th",
    "2 Thessalonians": "2th",
    "1 Timothy": "1tim",
    "2 Timothy": "2tim",
    "Titus": "tit",
    "Philemon": "philem",
    "Hebrews": "heb",
    "James": "jas",
    "1 Peter": "1pet",
    "2 Peter": "2pet",
    "1 John": "1jn",
    "2 John": "2jn",
    "3 John": "3jn",
    "Jude": "jude",
    "Revelation": "rev",
}
